import requests

url = "http://api.text.ru/post"

body = {
    "userkey": "acceef73c9f23e343146d38a83e0d6d6",
    "text": "TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API TESTING API"
}

a = requests.post(url=url,json=body,headers={"Content-Type": "application/json"})

print(a.text,a.status_code,sep="\n")